version: "3.7"
services:
  postgres:
    image: postgres:13.3-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./bin/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker-databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # we can list several comma separated databases here
      POSTGRES_MULTIPLE_DATABASES: account

  account:
    build:
      context: .
      dockerfile: ./account-service/Dockerfile
    container_name: account
    restart: always
    ports:
      - "2000:8002"
    depends_on:
      - postgres
    environment:
      # this will resolve to jdbc:postgresql://postgres:5432/account
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: account
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres:
    external: false
