version: "3.7"
services:
  postgres:
    image: postgres:13.2
    container_name: $DB_HOST
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./bin/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker-databases:/docker-entrypoint-initdb.d
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      # we can list several comma separated databases here
      POSTGRES_MULTIPLE_DATABASES: "\"$DB_NAME\""

  account:
    build:
      context: .
      dockerfile: ./account-service/Dockerfile
    container_name: account
    restart: always
    ports:
      - 2000:8002
    depends_on:
      - postgres
    environment:
      # this will resolve to jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD

volumes:
  postgres:
    external: false
